project: 
  type: website
  output-dir: "." 

website:
  title: "Caitlin Roos"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Projects
        menu: 
          - text: Fish Sustainability
            href: Fish_Sustainability_Project.pdf
          - text: The Ear as a Fourier Trnasformation
            href: Least_Squares.pdf
          - text: Dynamical Sysytems & Chaos
            href: Topology_Pres.pdf
        
      
  page-footer: 
    center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>© Caitlin Roos, 2025"

format:
  html:
    theme: 
      light: sandstone # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

